[package]
name = "servo_gui"
version = "0.0.1"
authors = ["The Servo Project Developers"]
license = "MPL-2.0"
publish = false

[features]
default = ["unstable"]
unstable = ["libservo/unstable"]

[dependencies]
euclid = "0.19"
gleam = "0.6"
glutin = "0.18"
lazy_static = "1"
libservo = {path = "../../components/servo"}
tinyfiledialogs = "3.0"
winit = {version = "0.17", features = ["icon_loading"]}

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
osmesa-sys = "0.1.2"

[target.'cfg(target_os = "linux")'.dependencies]
x11 = "2.0.0"

#[target.'cfg(target_os = "windows")'.dependencies]
#winapi = "0.2"
#user32-sys = "0.2"
#gdi32-sys = "0.2"

[target.'cfg(target_os = "macos")'.dependencies]
osmesa-src = {git = "https://github.com/servo/osmesa-src"}

[target.x86_64-unknown-linux-gnu.dependencies]
osmesa-src = {git = "https://github.com/servo/osmesa-src"}
