[package]
name = "servo_gui"
version = "0.0.1"
authors = ["The Servo Project Developers"]
license = "MPL-2.0"
publish = false

[features]
default = ["unstable"]
unstable = ["libservo/unstable"]

[dependencies]
euclid = "0.19"
gleam = "0.6"
glutin = "0.18"
lazy_static = "1"
libservo = {path = "../../components/servo"}
tinyfiledialogs = "3.0"
winit = {version = "0.17", features = ["icon_loading"]}
